clc;
clear all;
close all;
w1 = 0.2 * pi; 
w2 = 0.6 * pi;  
a1 = 0.8;        
a2 = 0.2;        
disp('Enter the Passband frequency w1 = '); disp(w1);
disp('Enter the Stopband frequency w2 = '); disp(w2);
disp('Enter the Passband ripple a1 = '); disp(a1);
disp('Enter the Stopband ripple a2 = '); disp(a2);
[N1, Wc1] = butt_biord(w1, w2, a1, a2);
[num1, den1] = butter(N1, Wc1, 'high', 's');
disp('HPF ANALOG FILTER TRANSFER FUNCTION');
disp('Numerator coefficients:'); disp(num1);
disp('Denominator coefficients:'); disp(den1);
[b1, a1] = bilinear(num1, den1, 1);
disp('HPF DIGITAL FILTER TRANSFER FUNCTION');
disp('Numerator coefficients:'); disp(b1);
disp('Denominator coefficients:'); disp(a1);
[mag1, angle1] = freqz(b1, a1, 512);
magnitude = 20 * log10(abs(mag1));
figure(2);
plot(angle1/pi, magnitude);
grid on;
title('High Pass Butterworth Filter');
xlabel('Normalized Frequency (\times\pi rad/sample)');
ylabel('Magnitude (dB)');
